<?php
	$this->load->view("designer/header");
?>

 <script type="text/javascript">
		$(document).ready(function(e) {
            $('#slug-help-btn').click(function(e) {
				$('#slug-view-help').slideDown('slow');
                $('#slug-help-btn').hide();
            });
			$('#slug-help-btn-close').click(function(e) {
				$('#slug-view-help').slideUp('fast');
                $('#slug-help-btn').show();
            });
			$('#dp-help-btn').click(function(e) {
				$('#dp-view-help').slideDown('slow');
                $('#dp-help-btn').hide();
            });
			$('#dp-help-btn-close').click(function(e) {
				$('#dp-view-help').slideUp('fast');
                $('#dp-help-btn').show();
            });
		 });
    </script>

<div id="Middle-Div">
<div id="slug-view">
	<h2>You have a Job Pending</h2>
	<p><label for="name">Order Id</label></p>
    <input type="text" name="id" id="id" value="<?php echo $pending_job['order_no']; ?>" readonly />
    <p style="padding-top: 50px;"><a id="slug-help-btn" href="javascript: void(0);" style="text-decoration: none; color: #666;">Slug Help</a></p>
    <div id="slug-view-help" style=" display: none; width: 90%; margin-top: 50px; padding-top: 10px; border-top: thin solid #999;">
    <p>
    Steps to follow:-<br/><br/>
    1. Enter Order Id (Order No.) in ORDER ID field<br/>
    2. Click on Submit Query<br/>
    3. Copy & Paste the  slug to Indesign File<br/>
    4. Once the ad is completed, click on END TIME Button<br/>
    5. DP is automatically Calculated<br/>
    Note: Please Do not Modify / Change the Slug Generated by the tool.<br/><br/>
    Issues:-<br/><br/>
    <strong>Q:</strong> - Order No. not found/Slug Not Correct ?<br/>
    <strong>Ans:</strong> - Contact your CSR/CWC  in person/skype/Phone...immediately and start from step 1 for the next job.<br/><br/>CSR Contact: 08042467800 / 811 / 812</p>
    <p><a id="slug-help-btn-close" href="javascript: void(0);" style="text-decoration: none; color: #666;">Close</a></p>
    </div>
  </div>

<div id="dp-view">
	
	<form name="form1" action="<?php echo base_url().index_page().'designer/home/dp_end';?>" method="post" >
	<?php
		echo "<p>".$pending_job['slug']."</p>";
		echo "<p>".$pending_job['start_time']."</p>";
	?>
	
	<input type="text" name="oid" id="oid" value="<?php echo $pending_job['order_no']; ?>" readonly style="visibility:hidden" />
	 <div id="slug-btn">
	<input type="submit" name="end_time" id="end_time" value="End Time" onclick="return confirm('Are you sure you want to end the job?');" />
    <br/><br/>
	<input type="submit" name="end_job" id="end_job" value="End Job" onclick="return confirm('Are you sure you want to end the Job Session?');" />

	</div>
    <p style="text-align: right;"><a id="dp-help-btn" href="javascript: void(0);" style="text-decoration: none; color: #666;">If category wrong click here</a></p>
    <div id="dp-view-help" style=" display: none; background:#333333; padding: 10px; margin-top: 30px; border-radius: 5px; color: #FFF;">
       <p style="margin: 0; padding-bottom: 5px;">Category</p>
		<p style="margin: 0;"><select name="category" ></p>
	<option value=""> select </option>
	<?php
	$category = $this->db->get('cat_minmax')->result_array();
	foreach($category as $cn)
		{
	?>
	<option value='<?php echo $cn['cat'] ?>'  > <?php echo $cn['cat']; ?> </option>
	<?php
		}
	?>
	</select>
    <p>Comments</p>
	<p style="margin:0;"><textarea id="comments" name="comments"></textarea></p>
    <p style="margin:0; color: #CCC;">*Category Selected Here will be used only for analysis.</p>
     <p><a id="dp-help-btn-close" href="javascript: void(0);" style="text-decoration: none; color: #666;">Close</a></p>
        </div>
	</form>

</div>

<div id="Back-btn"><a href="<?php echo base_url().index_page().'designer/home/';?>">Back</a></div>
</div>   

<?php
	$this->load->view("designer/footer");
?>